### ISSUE TITLE
[TB] Migrate to Zoom

### ISSUE THREAD

**Issue by evangk6** [finos/a11y-theme-builder#483]
## Problem/Concern

Our recurring meetings will need to be moved over to Zoom.
It was also suggested that we might each have our own FINOS accounts.

**Comment by aaronreed708** [comment]
So this issue is to create a re-occurring, weekly meeting for Thursdays from 9:15 - 10:00am inviting the Theme Builder community.  I have school dropoff and I assume that I'll be leading at least the first few meetings so for now we'll use 9:15am start time.  @TheJuanAndOnly99 or @maoo, can we get these setup as Zoom through FINOS?  Otherwise I'll setup a Google Meet.

This meeting should require:

Lise, Keith, Bryce, Evan, Aaron, Cody, Chima, Dorothy

With optionals:

Andy, Dan, Paula, Mike, Kicki

**Comment by TheJuanAndOnly99** [comment]
Hi @aaronreed708 yes we can set up the call starting next week. We'll provide you 1 licensed Zoom "project" account which can be used to open and manage meetings by you or anyone from the maintainers team. We'll share the credentials to that account with you as soon as they are ready via slack (I've just sent you an invite to join). Then we can schedule the call and invite everyone.

Can you specify the time zone for the call I want to make sure there are no mistakes when it comes to scheduling it.

**Comment by aaronreed708** [comment]
9:15am US Eastern time, please.

**Comment by TheJuanAndOnly99** [comment]
Hey @aaronreed708 you should have gotten a meeting invite. I've added everyone except Cody, Chima, Dorothy, Mike, and Kicki as I don't have their email addresses. Please feel free to add them to the invite or to send me their email address and I will add them.

**Comment by aaronreed708** [comment]
Held first Zoom call today.  Closing.
