### ISSUE TITLE
[REQUEST] Font setting sliders

### ISSUE THREAD

**Issue by Chessel** [finos/a11y-theme-builder#545]
## Suggestion/Concern
1. when setting the font styles the slides make it hard to get round numbers for the font sizes. It is also hard to set it back to the initial  settings.
2. The global font-weight variable is set to 700 however every single heading styles is set to 400 therefore I have to go inside each one of the m and set it manually

## Proposed Solution
1. Change slider to a different mechanism
2. Apply global setting to each individual style

**Comment by aaronreed708** [comment]
@aaronreed708 to follow up with @Chessel

**Comment by Chessel** [comment]
Checked on the Theme Builder Website and the Display font weight changes for each individual display style when the user change the global weight.
<img width="1108" alt="Screen Shot 2023-10-19 at 12 07 53 PM" src="https://github.com/finos/a11y-theme-builder/assets/8109233/4ba5b33b-e0b5-4416-ab47-7b1ba2d2d006">

**Comment by aaronreed708** [comment]
Select Font->Font Settings in Typography Atoms
Change the secondary font weight that affects displays and headers.  Note the value.

Select Font->Display & Header Styles
Heading/Display Font Weight field now has the value set in the secondary font weight field.

However, if you change the value in the Heading/Display Font Weight field, it does NOT affect the secondary font weight field.

Looking at the other Font Settings, like Body Style, the only way to control them globally is from the Font Settings pane.  That should be the same for Display & Header Styles

@lwnoble @evangk6 Do you agree with my conclusion?  Or is there a reason that this field is here, modifiable, yet not two way linked to the Secondary Font Weight field in Font Settings.

**Comment by evangk6** [comment]
I agree with your conclusion: global font settings should change the individual typography style settings but not vice versa, to allow for optional customization. I believe that is currently working as intended and fixed since this issue.

As for the slider, we need to discuss with Lise what the intention of that is. SecondaryFontWeight has since been added which may be the same thing here. Either way, I will make it so that the values stick to the nearest 100.

**Comment by aaronreed708** [comment]
I verified that the Display & Header Styles -> Heading/Display Font Weight field no longer changes the Font Settings -> Secondary Font Weight field.  But I guess I don't understand why the Display & Header Styles -> Heading/Display Font Weight field isn't readonly.  If Font Settings -> Secondary Font Weight field is changed, it will overwrite any custom value that I gave Display & Header Styles -> Heading/Display Font Weight and I may never realize it since they are on two separate panels.  I would say that if each field is modifiable, then they need to be linked to a common value.  Otherwise I think that  Display & Header Styles -> Heading/Display Font Weight should be readonly, maybe with some link back to the field in settings that will modify it or hover help pointing back to the field in Font Settings panel.
