### ISSUE TITLE
[TB] Font Weight Issues

### ISSUE THREAD

**Issue by lwnoble** [finos/a11y-theme-builder#693]
## Problem/Concern

Despite showing the font weights in the drop-down by default as:
<img width="749" alt="Screenshot 2023-10-26 at 10 40 49 AM" src="https://github.com/finos/a11y-theme-builder/assets/6164440/63b2f053-d2ba-4e20-851c-418b13263dd1">

The Code shows the following:
<img width="832" alt="Screenshot 2023-10-26 at 10 39 10 AM" src="https://github.com/finos/a11y-theme-builder/assets/6164440/2dc295aa-312a-46f7-8521-85e9a10b6d5f">

* [link to problem content]()

**Comment by evangk6** [comment]
as mentioned in #668 the issue was with the sample systems. Seeing this issue, I went ahead and changed the sample systems in https://github.com/finos/a11y-theme-builder/pull/705. You'll need to pull these changes, and may lose any other changes you have (unless you simply update the sample systems in your browser).

**Comment by aaronreed708** [comment]
@evangk6 says this is fixed, closing.
